### PR TITLE
Remove start page and redirect / to GOV.UK start page

### PR DESCRIPTION
**Pull request by issyl0**
- This matches the guidance in the Service Manual that every service should start at GOV.UK: https://www.gov.uk/service-manual/technology/get-a-domain-name#ensure-users-start-their-journey-on-govuk

### CODE REVIEW

**Review by bilbof — APPROVED** [review]
Does the translations file also need updating?

**Comment by issyl0** [comment]
@bilbof I didn't realise we had a feature test for the start page. I completely removed it, I hope that's right. If you want me to test the redirect works then I can do, but my Cucumber is a bit rusty.

**Review by huwd — APPROVED** [review]

**Comment by bilbof** [comment]
No worries, I added it mainly as a demo for future e2e tests.

**Comment by issyl0** [comment]
> Does the translations file also need updating?

Good catch, thanks. That file shouldn't be any more complicated that it needs to be!

**Pull request merged**
