### PR TITLE
Change Dynimoid logging level to :info

### PR DESCRIPTION
**Pull request by huwd**
Trello: https://trello.com/c/CpNKGtCb/184-ensure-sensitive-data-doesnt-go-to-logit-splunk

**DRAFT PENDING TEST ON STAGING**

# Test
- Get this on staging
- Noodle around
  - Normal browse behaviour
  - Cause an error
  - Submit a stand-in for PII
  - Cause validation error
- Logs should have No PII
- Logs should have validation errors
- Logs should have errors
- check the logs since deploy

# What
tweak the logging levels in production to prevent PII getting in, but ensure we still get useful logs on validation attempts

# Why
Keep cyber happy, keep debugging devs happy.

### CODE REVIEW

**Comment by theseanything** [comment]
Do turns out logs can have PII in them 😢 - We ended up having reduce the log level  https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form/pull/141

**Review by theseanything — CHANGES_REQUESTED** [review]
Turns out logs can have PII in them 😢 - We ended up having reduce the log level #141. I think Dynamoid is sharing the default Rails logger - so we are suppressing all Rails log with setting. Maybe need to make a separate logger? Think we need info level for rails as validation errors probably aren't "application errors".

**Comment by richardTowers** [comment]
I suggest we pause the prod bit of the pipeline, merge this, let it deploy to staging, run through a couple of journeys, have a look through the logs for any PII, revert it if we're not happy, unpause the pipeline otherwise.

**Comment by theseanything** [comment]
Hmm even at :info level I'm seeing logs such as:
```
Started POST "/contact-details" for ::1 at 2020-03-30 12:10:08 +0100
Processing by CoronavirusForm::ContactDetailsController#submit as HTML
  Parameters: {"authenticity_token"=>"Xq6KfiLO3qkUDHCmCv64JSO6RRSrdWFQfZXilSGlmqo9hMVMM4YjHKpYbHbDtVfrosCo7E/UbZ+g4m4AAeVGew==", "phone_number_calls"=>"07000000", "phone_number_texts"=>"07000000", "email"=>"user@email.com"}
```
Which means even if we set Dynamoid at a lower lever, we'd still log PII

**Comment by theseanything** [comment]
But we might be able to use something like this: https://guides.rubyonrails.org/action_controller_overview.html#parameters-filtering

**Comment by theseanything** [comment]
I've created another PR that might solve this issue https://github.com/alphagov/govuk-coronavirus-vulnerable-people-form/pull/205

**Pull request closed without merging**
